### ISSUE TITLE
게임리포트 분류 방식 변경

### ISSUE THREAD

**Issue by minsu9486** [gamereport/gamereport#4]
# 게임리포트 분류 방식 변경

## 의견

날짜별 세분화하여 파일을 저장하는 것이 효율적인지 고민됩니다. 달 또는 분기별로 나누는 것으로도 충분하다고 생각되어 폴더를 줄였으면 합니다. 여러분의 생각은 어떻습니까?

## 예시 

분기별로 카테고리를 나누고 파일명에 몇 주차인지 정도 추가했으면 좋겠습니다.

* gamereport
    * 2017
        * 4분기
            * 1주차_!@#.md
    * 2018
        * 1분기
            * 2주차_568_분석.md
            * 3주차_abc_분석.md
            * 3주차_abc_자료.md
        * 2분기

**Comment by Heeeeeeju** [comment]
@minsu9486 병국이가 처음에 세분화시켜서 거기 따라서 해놨던건데 이 의견도 괜찮다고 생각합니다. 다음 스터디 때 한 번 얘기해봅시다.

**Comment by minsu9486** [comment]
회의 결과 분기별로 나누어 파일을 저장하기로 결정되어 이슈를 닫겠습니다.
