### ISSUE TITLE
깃허브 플로우 사용 건의

### ISSUE THREAD

**Issue by byeonggukgong** [gamereport/gamereport#5]
현재는 모든 멤버가 직접 저장소에 커밋 푸시를 하고있는데, 커밋 메세지 일관성이 떨어져 가독성이 떨어지고 혹시 모를 충돌 가능성도 존재합니다.  그래서 저장소를 포크해서 풀 리퀘스트를 요청하는 **깃허브 플로우** 방식으로 저장소를 관리하는 것에 대해 물어봅니다.

**Comment by minsu9486** [comment]
Innnnn→ter↗es→ting↘... buuuu→t↘, I↗ th→in↘k↗
커밋하는게 중복되는 한 파일 내에서 하는게 아니라, 각자 맡은 영역을 개인별 파일에 커밋하는 작업이라 충돌이 별로 일어날 것 같지는 않아서(귀찮으니), 효율을 따져서 그냥 기존 프로세스를 유지하는 것이 좋다고 생각합니다만! "깃허브 플로우" 방식을 해보지 않은 입장에서는 흥미롭고 해보고도 싶으니, **실험적인 정신으로는 찬성**.

**Comment by byeonggukgong** [comment]
또 다른 깃허브 플로우의 장점은 모두가 풀 리퀘스트를 하기도 하지만 검증도 함께하기 때문에 변경 사항에 대한 검증도 가능합니다.

**Comment by byeonggukgong** [comment]
깃허브 플로우 사용 건의에 대해 찬성 의견이 많아 사용하기로 했습니다.
